apiVersion: v1
kind: ServiceAccount
metadata:
  name: fortress-dashboard-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fortress-dashboard-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "namespaces", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fortress-dashboard-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fortress-dashboard-role
subjects:
- kind: ServiceAccount
  name: fortress-dashboard-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortress-dashboard-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortress
  template:
    metadata:
      labels:
        app: fortress
    spec:
      serviceAccountName: fortress-dashboard-sa
      containers:
        - name: fortress-dashboard
          image: fortressvnetdevb0d6a535acru9s3l6.azurecr.io/fortress-dashboard:latest
          ports:
            - containerPort: 3000
          env:
            - name: PGHOST
              value: "PGHOST_PLACEHOLDER"
            - name: PGUSER
              value: "PGUSER_PLACEHOLDER"
            - name: PGPASSWORD
              value: "PGPASSWORD_PLACEHOLDER"
            - name: PGDATABASE
              value: "PGDATABASE_PLACEHOLDER"
            - name: PGSSLMODE
              value: "require"
            - name: APPGW_ID
              value: "APPGW_ID_PLACEHOLDER"
            - name: AKS_ID
              value: "AKS_ID_PLACEHOLDER"
            - name: DB_ID
              value: "DB_ID_PLACEHOLDER"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: fortress-service
spec:
  selector:
    app: fortress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
